# Generated by Django 3.2.5 on 2021-07-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210702_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
